### ISSUE TITLE
hbonds are backwards 50% if @atom order is modified

### ISSUE THREAD

**Issue by jewettaij** [m-bone/moltemplate-DREIDING#1]
Hi Matt
   I just realized a problem that could be effecting simulation results for DREIDING users.  I am fixing it in a half-assed way by manually changing the atom type order at the beginning of the "dreiding.lt" file.  ("Solution #2" below...)

   You don't have to modify anything, but I wanted to post a copy of the issue here to make sure you are aware of it, in case you have made your own local copy of "dreiding.lt".

*Here is the text I copied from [the moltemplate issue page](https://github.com/jewettaij/moltemplate/issues/46):*

- In the "dreiding.lt" file, in each corresponding *pair_coeff* command for these interactions, we are assuming that the first atom type is a hydrogen bond donor, because we invoke the *pair_coeff* command using the "i" argument.  For details, see the documentation for [*pair_style hbond/dreiding/lj*](https://lammps.sandia.gov/doc/pair_hbond_dreiding.html).
- However all *pair_coeff i j...* commands requires that *i≤j*.  (See the documentation for [pair_coeff](https://lammps.sandia.gov/doc/pair_coeff.html).)
- To comply with this requirement, *moltemplate.sh* actually has a post-processing step where it looks inside all of the *pair_coeff* commands and swaps the order of the atom types whenever *i>j*.  When it does this, it only considers the *i* and *j* numbers (after the @atom types have been converted into numbers).  It does not know whether *i* or *j* correspond to donor or acceptor atom types.
- In *moltemplate*, by default, @atom types are assigned to numbers according to the order in which they first appear in any of the user's LT files.  Currently (as of 2021-4-08), the donor atom types (@atom types ending in "_hd") are interspersed with with the acceptor atom types (ending in "_ha").
- This means that, approximately half of the time, LAMMPS will confuse the donor and acceptor atoms in each hbond/dreiding/lj interaction.

There are two solutions to this problem:
1) Edit the *postprocess_coeffs.py* file and make it aware of the quirks of the *hbond/dreiding/* pair_coeff syntax.
2) Modify the "dreiding.lt" file to make sure *all* of the donor atom types are mentioned before *any* of the acceptor atom types.  This is the easiest solution, and it works *most* of the time.  But it will fail if the user decides to override the @atom number assignments (by invoking *moltemplate.sh* using either the "-a" or "-b" arguments on those atom types).  It will also fail in the unlikely event that users decide to refer to an acceptor atom (eg "@atom:N_R_b1_d2_ha") somewhere at the very beginning of their LT file, before the *import "dreiding.lt"* command is issued (causing it to be assigned to *1*).

For now (2021-4-08), I will try solution 2.  Later, I will try solution 1 when I have more time.
Meanwhile, I will leave this issue on the tracker until it is resolved.

-Andrew

**Comment by jewettaij** [comment]
Hi Matt.
   The "dreiding.lt" file included with the current version (v2.19.8) of moltemplate has been updated address this issue.  If you are using this for your research, please use that version of the "dreiding.lt" file and let me know if you spot any problems.

I will also include the message that I posted to the moltemplate issue tracker:

"I *think* dreiding.lt is working now.  However if you use hydrogen bonds with DREIDING, then please double-check the "system.in.settings" files created by moltemplate.sh, and check each "pair_coeff" command containing the text "hbond/dreiding/lj".  Make sure that the atom types are listed in the correct order, with donor atom types listed before (ie. to the left of) acceptor atoms.  Before doing this, I suggest running "cleanup_moltemplate.sh" first.  (Otherwise the number of pair_coeff commands in the "system.in.settings" file will be far too large to check by hand.)"

I'll let you know when I fix the "postprocess_coeffs.py" file.  ("Solution 1" above.)

Hi

**Comment by m-bone** [comment]
Hi Andrew,

Thanks for pointing this out, I'll look to sort out the ordering in the version I have here and push out an update. I had my suspicions that something wasn't quite right, but I've been writing the python code for the mapping problem recently so haven't been doing much lammps modelling. Hopefully have something new on mapping task soon, though, as I should have guessed, it's a much larger challenge than I initially thought!

Cheers, Matt

**Comment by m-bone** [comment]
This has now been fixed with the latest version of the main branch. The dreiding.lt file here now matches the one in the main Moltemplate repo so there is no need for a pull request.

Best, Matt

**Comment by jewettaij** [comment]
That's great!
Thanks.
